AWSTemplateFormatVersion: "2010-09-09"
Description: API Gateway with websocket integration

Resources:
  WebSocketAPI:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: $request.body.action
      ApiKeySelectionExpression: $request.header.x-api-key
      Name: !Sub "${AWS::StackName}-api"


  ProductionStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      ApiId: !Ref WebSocketAPI
      StageName: prod
    DependsOn: WebSocketAPI

  ProductionDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    Properties:
      ApiId: !Ref WebSocketAPI
      StageName: prod
    DependsOn:
      - ProductionStage
      # Need all routes built before doing a deployment
      - DefaultRoute
      - ConnectRoute
      - DisconnectRoute
      - Authorizer


  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: $default
      Target: !Join [/, [integrations, !Ref DefaultTarget]]

      # websocket authentication args
      ApiKeyRequired: false
      AuthorizationType: NONE
    DependsOn:
      - WebSocketAPI
      - DefaultTarget

  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: $connect
      Target: !Join [/, [integrations, !Ref DefaultTarget]]
      ApiKeyRequired: false
      AuthorizationType: CUSTOM
      AuthorizerId: !Ref Authorizer
    DependsOn:
      - WebSocketAPI
      - DefaultTarget
      - Authorizer

  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey:  $disconnect
      Target: !Join [/, [integrations, !Ref DefaultTarget]]
      ApiKeyRequired: false
      AuthorizationType: NONE
    DependsOn:
      - WebSocketAPI
      - DefaultTarget

  EchoRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: Echo
      Target: !Join [/, [integrations, !Ref DefaultTarget]]

      # websocket authentication args
      ApiKeyRequired: false
      AuthorizationType: NONE
    DependsOn:
      - WebSocketAPI
      - DefaultTarget

  QuoteRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocketAPI
      RouteKey: Quote
      Target: !Join [/, [integrations, !Ref DefaultTarget]]

      # websocket authentication args
      ApiKeyRequired: false
      AuthorizationType: NONE
    DependsOn:
      - WebSocketAPI
      - DefaultTarget

  DefaultTarget:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocketAPI
      IntegrationType: AWS_PROXY
      IntegrationUri: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${DefaultLambdaEndpoint.Arn}/invocations'
    DependsOn:
      - WebSocketAPI
      - DefaultLambdaEndpoint

  DefaultLambdaEndpointPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt DefaultLambdaEndpoint.Arn
      Principal: apigateway.amazonaws.com
      # SourceArn: !GetAtt WebSocketAPI.Arn
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*'
    DependsOn:
      - WebSocketAPI
      - DefaultLambdaEndpoint

  DefaultLambdaEndpoint:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.7
      Role: !GetAtt LambdaEndpointRole.Arn
      Environment:
        Variables:
          EVENT_BUS: !ImportValue example-event-bus-id
      Code:
        ZipFile: |
          import json
          import os
          import boto3
          eventbridge = boto3.client("events")
          handlers = {
              "Echo": lambda event: {"sender": event["requestContext"]["connectionId"], "message": event["body"]["message"]},
              "Quote": lambda event: {"name": event["requestContext"]["connectionId"]},
              "$connect": lambda event: {"name": event["requestContext"]["authorizer"]["principalId"], "connectionId": event["requestContext"]["connectionId"]},
          }
          def lambda_handler(event, context):
              print(json.dumps(event))
              client = boto3.client(
                "apigatewaymanagementapi",
                # URL of API Gateway request originated from
                endpoint_url=f"https://{event['requestContext']['domainName']}"
                             f"/{event['requestContext']['stage']}/",
              )
              connection_id = event["requestContext"].get("connectionId")
              route_key = event["requestContext"]["routeKey"]
              if route_key in ("$connect", "$disconnect"):
                  pass
              elif route_key not in handlers:
                  client.post_to_connection(
                      Data=f'Unrecognized action "{route_key}".'.encode(),
                      ConnectionId=connection_id,
                  )
              else:
                  client.post_to_connection(
                      Data=b"Your message was recieved and put on the bus!",
                      ConnectionId=connection_id,
                  )
              handler = handlers.get(route_key, lambda _e: {})
              try:
                  event["body"] = json.loads(event["body"])
              except KeyError:
                  # $connect & $disconnect don't have a body and I'm lazy
                  body = {}
              detail = handler(event)
              if detail:
                  eventbridge.put_events(Entries=[
                      {
                          "Source": "DefaultLambdaEndpoint",
                          "Resources": [context.invoked_function_arn],
                          "DetailType": event["requestContext"]["routeKey"],
                          "Detail": json.dumps(detail),
                          "EventBusName": os.getenv("EVENT_BUS"),
                      },
                  ])
              return {"statusCode": 200}
    DependsOn:
      - LambdaEndpointRole

  LambdaEndpointRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: !Sub '${AWS::StackName}-api-connections'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - "execute-api:ManageConnections"
                # Resource: !GetAtt WebSocketAPI.Arn
                Resource: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*'
        - PolicyName: !Sub '${AWS::StackName}-put-events'
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: "*"  # PutEvents does not restrict at the resource level
    DependsOn:
      - WebSocketAPI


  Authorizer:
    Type: AWS::ApiGatewayV2::Authorizer
    Properties:
      ApiId: !Ref WebSocketAPI
      AuthorizerType: REQUEST  # Web Socket APIs must use REQUEST
      AuthorizerUri: !Sub 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaAuthorizer.Arn}/invocations'
      Name: !Sub "${AWS::StackName}-authorizer"
      IdentitySource:
        # Native WebSocket client does not support headers for sockets.
        # For this example, ?name=xxx will act as an authentication token
        - route.request.querystring.name
    DependsOn:
      - LambdaAuthorizer

  LambdaAuthorizer:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.7
      Role: !GetAtt LambdaAuthorizerRole.Arn
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print(event)
              response = {
                  "principalId": event["queryStringParameters"]["name"],  # This would be the user id
                  "policyDocument": {
                      "Version": "2012-10-17",
                      "Statement": [
                          {
                              "Action": "execute-api:Invoke",
                              "Effect": "Allow",
                              "Resource": event["methodArn"],
                          }
                      ],
                  },
                  "context": {
                      "foo": "bar",
                  },
              }
              print(response)
              return response
    DependsOn:
      - LambdaAuthorizerRole

  LambdaAuthorizerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    DependsOn:
      - WebSocketAPI

  LambdaAuthorizerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt LambdaAuthorizer.Arn
      Principal: apigateway.amazonaws.com
      # SourceArn: !GetAtt WebSocketAPI.Arn
      SourceArn: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*'
    DependsOn:
      - WebSocketAPI
      - LambdaAuthorizer


Outputs:
  WebSocketApiArn:
    Description: Arn of WebSocketAPI
    Value: !Sub 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${WebSocketAPI}/*'
    Export:
      Name: example-websocket-api-arn

  WebSocketUrl:
    Description: ws:// URL of deployed WebSocketAPI to connect to
    Value: !Sub "wss://${WebSocketAPI}.execute-api.${AWS::Region}.amazonaws.com/${ProductionStage}"
    Export:
      Name: example-websocket-wss-url

  ConnectionsUrl:
    Description: >
      https:// URL of deployed WebSocketAPI to manage connections with.
      Use as endpoint_url argument for apigatewaymanagementapi clients.
    Value: !Sub "https://${WebSocketAPI}.execute-api.${AWS::Region}.amazonaws.com/${ProductionStage}"
    Export:
      Name: example-websocket-http-url
